pipeline {
    agent any

    stages {
        stage('Build and Package') {
            steps {
                build job: 'plexmediahelper'
            }
        }
        stage('Deploy to Portainer') {
            steps {
                build job: 'redeploy_stack_sh'
            }
        }
    }
}